# Copyright (C) 2026 D. Brandmeyer
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
"""Per-instance directory layout (Prompt C5).

Every instance lives in one self-contained directory so "direct runtime
access remains available" (PLAN Section 7) is literally true: an operator
can `cd` into it and run the runtime's own compose commands. Layout:

    <data_root>/<name>/
        docker-compose.single.yml   # generated by ops/compose.py
        .env                        # compose-level vars (PUID/PGID, host
                                     # ports, DATA_HOST_DIR) -- read by
                                     # `docker compose` itself for variable
                                     # substitution, never by the container.
        data/
            .env                    # container-level vars (SECRET_KEY,
                                     # DEPLOY_MODE, PUBLIC_URL, ...) -- the
                                     # compose file's env_file.
            job-squire.db           # created by the app on first boot.
            uploads/

This whole directory -- not just data/ -- is what a C8 backup archive
needs to capture: it is the thing that contains SECRET_KEY (PLAN Section
7's backup design is explicit that the archive "necessarily contains that
instance's SECRET_KEY"). So this is also the value stored in the registry's
`data_dir` field (Instance.data_dir): the one directory that is the whole
instance.
"""
from __future__ import annotations

import os
from pathlib import Path

DATA_ROOT_ENV_VAR = "JOB_SQUIRE_HOME"
COMPOSE_FILENAME = "docker-compose.single.yml"
COMPOSE_ENV_FILENAME = ".env"
DATA_DIRNAME = "data"
DATA_ENV_FILENAME = ".env"
DB_FILENAME = "job-squire.db"  # must match app/__init__.py's DATABASE_URL default


def default_data_root() -> Path:
    """Where instance directories live unless overridden.

    `~/job-squire/` -- matches the example path in
    docs/PLAN-deployment-modes.md Section 4 (`/Users/dan/job-squire/castelo`).
    `JOB_SQUIRE_HOME` lets tests (and an operator with unusual disk layout
    needs) redirect this without monkeypatching `Path.home`.
    """
    override = os.environ.get(DATA_ROOT_ENV_VAR)
    if override:
        return Path(override)
    return Path.home() / "job-squire"


def instance_root(name: str, data_root: Path | None = None) -> Path:
    return (data_root if data_root is not None else default_data_root()) / name


def compose_path(root: Path) -> Path:
    return root / COMPOSE_FILENAME


def compose_env_path(root: Path) -> Path:
    return root / COMPOSE_ENV_FILENAME


def data_dir(root: Path) -> Path:
    return root / DATA_DIRNAME


def data_env_path(root: Path) -> Path:
    return data_dir(root) / DATA_ENV_FILENAME


def sqlite_db_path(root: Path) -> Path:
    return data_dir(root) / DB_FILENAME
