# Copyright (C) 2026 D. Brandmeyer
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
"""Per-instance directory layout.

Every instance lives in one self-contained directory so direct runtime
access always stays available: an operator can `cd` into it and run the
runtime's own compose commands. Layout:

    <data_root>/<name>/
        docker-compose.yml          # generated by ops/compose.py
        .env                        # compose-level vars (PUID/PGID, host
                                     # ports) -- read by `docker compose`
                                     # itself for variable substitution,
                                     # never by the container.
        data/
            .env                    # container-level vars (SECRET_KEY,
                                     # DEPLOY_MODE, PUBLIC_URL, ...) -- the
                                     # compose file's env_file, and the only
                                     # file that still lives here on the
                                     # host. Everything the app itself
                                     # writes (job-squire.db, uploads/,
                                     # candidate_profile.md, ...) lives
                                     # inside the container's /data instead,
                                     # which is a named Docker volume, not
                                     # this directory -- see ops/compose.py.

ops/backup.py's `create_backup` therefore reads two different things to
build one archive: this directory, walked directly on the host (it holds
SECRET_KEY -- the archive necessarily contains that instance's SECRET_KEY,
since decrypting the instance's stored secrets on restore requires it --
plus the compose files), and the named
volume's actual contents, read through the running container via
`docker/podman exec` (app/backup_cli.py) since a named volume isn't a host
path the CLI can just walk. `restore_instance` reverses both halves. This
directory is still the value stored in the registry's `data_dir` field
(Instance.data_dir) -- it's the one place on the host that identifies the
instance, even though it no longer holds all of the instance's data.
"""
from __future__ import annotations

import os
from pathlib import Path

DATA_ROOT_ENV_VAR = "JOB_SQUIRE_HOME"
COMPOSE_FILENAME = "docker-compose.yml"
COMPOSE_ENV_FILENAME = ".env"
DATA_DIRNAME = "data"
DATA_ENV_FILENAME = ".env"
DB_FILENAME = "job-squire.db"  # must match app/__init__.py's DATABASE_URL default


def default_data_root() -> Path:
    """Where instance directories live unless overridden.

    `~/job-squire/` (e.g. `/Users/dan/job-squire/castelo`).
    `JOB_SQUIRE_HOME` lets tests (and an operator with unusual disk layout
    needs) redirect this without monkeypatching `Path.home`.
    """
    override = os.environ.get(DATA_ROOT_ENV_VAR)
    if override:
        return Path(override)
    return Path.home() / "job-squire"


def instance_root(name: str, data_root: Path | None = None) -> Path:
    return (data_root if data_root is not None else default_data_root()) / name


def compose_path(root: Path) -> Path:
    return root / COMPOSE_FILENAME


def compose_env_path(root: Path) -> Path:
    return root / COMPOSE_ENV_FILENAME


def data_dir(root: Path) -> Path:
    return root / DATA_DIRNAME


def data_env_path(root: Path) -> Path:
    return data_dir(root) / DATA_ENV_FILENAME


def sqlite_db_path(root: Path) -> Path:
    return data_dir(root) / DB_FILENAME
